<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * A single message in a conversation's history — written by an agent, sent
 * by the client themselves (`is_client = true`, e.g. via the live chat
 * widget), or generated by the AI as a draft (`is_draft = true`) awaiting
 * approval. A draft is never shown to the client and never counted as "sent"
 * until an agent approves it (see ConversationController::approveDraft()).
 */
class Reponse extends Model
{
    use HasFactory;

    protected $fillable = [
        'conversation_id',
        'agent_id',
        'contenu',
        'is_draft',
        'is_client',
    ];

    protected function casts(): array
    {
        return [
            'is_draft' => 'boolean',
            'is_client' => 'boolean',
        ];
    }

    public function conversation(): BelongsTo
    {
        return $this->belongsTo(Conversation::class);
    }

    // For an AI-generated draft, agent_id points at the bot User (see
    // AutomationRule::bot()) until a real agent approves and effectively
    // takes ownership of the reply.
    public function agent(): BelongsTo
    {
        return $this->belongsTo(User::class, 'agent_id');
    }

    public function attachments(): HasMany
    {
        return $this->hasMany(Attachment::class);
    }
}
